<?php

/**
 * @file
 * Contains hook implementations for the acquia_cms_headless module.
 */

/**
 * Implements hook_menu_links_discovered_alter().
 */
function acquia_cms_headless_menu_links_discovered_alter(array &$links) {
  // Direct the Help link to our tour, leaving the help available to people who
  // know where it is.
  if (array_key_exists('help.main', $links)) {
    $links['help.main']['route_name'] = $links['acquia_cms_headless.api-dashboard']['route_name'];
    $links['help.main']['title'] = $links['acquia_cms_headless.api-dashboard']['title'];
    // Don't show our Tour link twice.
    unset($links['acquia_cms_headless.api-dashboard']);
  }
}

/**
 * Register headless twig file.
 *
 * Implements hook_theme().
 */
function acquia_cms_headless_theme($existing, $type, $theme, $path) {
  return [
    'acquia_cms_headless' => [
      'variables' => [],
    ],
    'acquia_cms_headless_checklist_form' => [
      'render element' => 'form',
    ],
    'acquia_cms_headess_title_markup' => [
      'variables' => [
        'module_name' => NULL,
        'current_step' => NULL,
      ],
    ],
  ];
}

/**
 * Remove configuration form state when module is uninstalled.
 *
 * Implements hook_modules_uninstalled().
 */
function acquia_cms_headless_modules_uninstalled(array $modules) {
  foreach ($modules as $module) {
    \Drupal::state()->delete('acms_' . $module . '_configured');
  }
}
